server:
  port: 8081

spring:
  application:
    name: bsy

  datasource:
    url: jdbc:mysql://localhost:3306/bsy?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: bsyuser
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  sql:
    init:
      mode: always
      platform: mysql
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql